# docker build --pull \
#    --build-arg CUDA_VER=10.2 \
#    --build-arg BASE_DIST=ubi8 \
#    --tag nvidia/samples/vectoradd-cuda10.2 --file Dockerfile .
#
ARG BASE_DIST
ARG CUDA_VER
FROM nvidia/cuda:${CUDA_VER}-devel-${BASE_DIST} AS builder

# FIXME: Hack due to lack of Appstream packages on the ubi8 repository
RUN dnf install -y \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/xorg-x11-proto-devel-2018.4-1.el8.noarch.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libglvnd-1.2.0-6.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libICE-1.0.9-15.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libICE-devel-1.0.9-15.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-libglapi-19.3.4-2.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libX11-xcb-1.6.8-3.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libSM-1.2.3-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libxshmfence-1.3-2.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libwayland-server-1.17.0-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXau-1.0.8-13.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libxcb-1.13.1-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXau-1.0.8-13.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXau-devel-1.0.8-13.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libxcb-devel-1.13.1-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libSM-devel-1.2.3-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libglvnd-opengl-1.2.0-6.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/hwdata-0.314-8.4.el8.noarch.rpm \
    http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/libpciaccess-0.14-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libdrm-2.4.100-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libdrm-devel-2.4.100-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libwayland-client-1.17.0-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-libgbm-19.3.4-2.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libwayland-client-1.17.0-1.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libglvnd-egl-1.2.0-6.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-libEGL-19.3.4-2.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libglvnd-egl-1.2.0-6.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-libEGL-19.3.4-2.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libglvnd-gles-1.2.0-6.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libglvnd-core-devel-1.2.0-6.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libX11-1.6.8-3.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libX11-devel-1.6.8-3.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXext-1.3.3-9.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXext-devel-1.3.3-9.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXfixes-5.0.3-7.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXi-1.7.9-7.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXxf86vm-1.1.4-9.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXt-1.1.5-12.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXt-devel-1.1.5-12.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXmu-1.1.2-12.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXmu-devel-1.1.2-12.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXdamage-1.1.4-14.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libglvnd-glx-1.2.0-6.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-libGL-19.3.4-2.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libglvnd-devel-1.2.0-6.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-libGL-devel-19.3.4-2.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/freeglut-3.0.0-8.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-libGLU-9.0.0-15.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXfixes-devel-5.0.3-7.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libXi-devel-1.7.9-7.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/gl-manpages-1.1-15.20161227.el8.noarch.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-libGLU-devel-9.0.0-15.el8.x86_64.rpm \
    http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/freeglut-devel-3.0.0-8.el8.x86_64.rpm

ARG CUDA_VER
RUN dnf install -y \
    cuda-samples-$(echo ${CUDA_VER} | sed -e 's/\./-/')

WORKDIR /usr/local/cuda/samples/0_Simple/vectorAdd/
RUN make

FROM nvidia/cuda:${CUDA_VER}-base-${BASE_DIST}
LABEL io.k8s.display-name="NVIDIA CUDA vectorAdd sample"
LABEL name="NVIDIA CUDA vectorAdd sample"
LABEL vendor="NVIDIA"
LABEL version="1.0.0"
LABEL release="N/A"
LABEL summary="NVIDIA container to validate GPU support"
LABEL description="See summary"

COPY ./LICENSE ./licenses/LICENSE


COPY --from=builder /usr/local/cuda/samples/bin/x86_64/linux/release/vectorAdd /tmp/vectorAdd

ENTRYPOINT ["/tmp/vectorAdd"]

